<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="0" failed="4" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-10-06T19:19:28 IST" name="guru99 customer" finished-at="2023-10-06T19:19:52 IST" duration-ms="24175">
    <groups>
      <group name="whitebox">
        <method signature="TC_Login_Guru99_001.login([Ljava.lang.Object;)[pri:0, instance:TestCases.TC_Login_Guru99_001@6f03482]" name="login" class="TestCases.TC_Login_Guru99_001"/>
      </group> <!-- whitebox -->
      <group name="functional">
        <method signature="TC_Login_Guru99_001.login([Ljava.lang.Object;)[pri:0, instance:TestCases.TC_Login_Guru99_001@6f03482]" name="login" class="TestCases.TC_Login_Guru99_001"/>
      </group> <!-- functional -->
      <group name="blackbox">
        <method signature="TC_Login_Guru99_001.login([Ljava.lang.Object;)[pri:0, instance:TestCases.TC_Login_Guru99_001@6f03482]" name="login" class="TestCases.TC_Login_Guru99_001"/>
      </group> <!-- blackbox -->
      <group name="daily build">
        <method signature="TC_Login_Guru99_001.login([Ljava.lang.Object;)[pri:0, instance:TestCases.TC_Login_Guru99_001@6f03482]" name="login" class="TestCases.TC_Login_Guru99_001"/>
      </group> <!-- daily build -->
      <group name="weekly build">
        <method signature="TC_Login_Guru99_001.login([Ljava.lang.Object;)[pri:0, instance:TestCases.TC_Login_Guru99_001@6f03482]" name="login" class="TestCases.TC_Login_Guru99_001"/>
      </group> <!-- weekly build -->
      <group name="regression">
        <method signature="TC_Login_Guru99_001.login([Ljava.lang.Object;)[pri:0, instance:TestCases.TC_Login_Guru99_001@6f03482]" name="login" class="TestCases.TC_Login_Guru99_001"/>
      </group> <!-- regression -->
      <group name="smoke">
        <method signature="TC_Login_Guru99_001.login([Ljava.lang.Object;)[pri:0, instance:TestCases.TC_Login_Guru99_001@6f03482]" name="login" class="TestCases.TC_Login_Guru99_001"/>
      </group> <!-- smoke -->
      <group name="sanity">
        <method signature="TC_Login_Guru99_001.login([Ljava.lang.Object;)[pri:0, instance:TestCases.TC_Login_Guru99_001@6f03482]" name="login" class="TestCases.TC_Login_Guru99_001"/>
      </group> <!-- sanity -->
    </groups>
    <test started-at="2023-10-06T19:19:28 IST" name="Guru99" finished-at="2023-10-06T19:19:52 IST" duration-ms="24175">
      <class name="TestCases.TC_Login_Guru99_001">
        <test-method is-config="true" signature="extentReports()[pri:0, instance:TestCases.TC_Login_Guru99_001@6f03482]" started-at="2023-10-06T19:19:27 IST" name="extentReports" finished-at="2023-10-06T19:19:28 IST" duration-ms="333" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- extentReports -->
        <test-method is-config="true" signature="initialiseBrowser(org.testng.ITestContext,java.lang.String,java.lang.String)[pri:0, instance:TestCases.TC_Login_Guru99_001@6f03482]" started-at="2023-10-06T19:19:28 IST" name="initialiseBrowser" finished-at="2023-10-06T19:19:38 IST" duration-ms="9974" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@45984654]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[https://www.demo.guru99.com/V4/index.php]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialiseBrowser -->
        <test-method is-config="true" signature="groupsstatus(java.lang.reflect.Method)[pri:0, instance:TestCases.TC_Login_Guru99_001@6f03482]" started-at="2023-10-06T19:19:39 IST" name="groupsstatus" finished-at="2023-10-06T19:19:39 IST" duration-ms="1" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void TestCases.TC_Login_Guru99_001.login(java.lang.Object[]) throws java.lang.InterruptedException,java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- groupsstatus -->
        <test-method signature="login([Ljava.lang.Object;)[pri:0, instance:TestCases.TC_Login_Guru99_001@6f03482]" started-at="2023-10-06T19:19:39 IST" name="login" data-provider="Guru_Customer_Details" finished-at="2023-10-06T19:19:41 IST" duration-ms="2002" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[[Ljava.lang.Object;@4a642e4b]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at TestCases.TC_Login_Guru99_001.login(TC_Login_Guru99_001.java:41)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="failedStatus(org.testng.ITestResult,java.lang.reflect.Method)[pri:0, instance:TestCases.TC_Login_Guru99_001@6f03482]" started-at="2023-10-06T19:19:42 IST" name="failedStatus" finished-at="2023-10-06T19:19:42 IST" duration-ms="482" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=login status=FAILURE method=TC_Login_Guru99_001.login([Ljava.lang.Object;)[pri:0, instance:TestCases.TC_Login_Guru99_001@6f03482] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void TestCases.TC_Login_Guru99_001.login(java.lang.Object[]) throws java.lang.InterruptedException,java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failedStatus -->
        <test-method is-config="true" signature="groupsstatus(java.lang.reflect.Method)[pri:0, instance:TestCases.TC_Login_Guru99_001@6f03482]" started-at="2023-10-06T19:19:42 IST" name="groupsstatus" finished-at="2023-10-06T19:19:42 IST" duration-ms="2" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void TestCases.TC_Login_Guru99_001.login(java.lang.Object[]) throws java.lang.InterruptedException,java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- groupsstatus -->
        <test-method signature="login([Ljava.lang.Object;)[pri:0, instance:TestCases.TC_Login_Guru99_001@6f03482]" started-at="2023-10-06T19:19:42 IST" name="login" data-provider="Guru_Customer_Details" finished-at="2023-10-06T19:19:44 IST" duration-ms="1488" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[[Ljava.lang.Object;@3b4086c1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at TestCases.TC_Login_Guru99_001.login(TC_Login_Guru99_001.java:41)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="failedStatus(org.testng.ITestResult,java.lang.reflect.Method)[pri:0, instance:TestCases.TC_Login_Guru99_001@6f03482]" started-at="2023-10-06T19:19:44 IST" name="failedStatus" finished-at="2023-10-06T19:19:45 IST" duration-ms="477" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=login status=FAILURE method=TC_Login_Guru99_001.login([Ljava.lang.Object;)[pri:0, instance:TestCases.TC_Login_Guru99_001@6f03482] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void TestCases.TC_Login_Guru99_001.login(java.lang.Object[]) throws java.lang.InterruptedException,java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failedStatus -->
        <test-method signature="login([Ljava.lang.Object;)[pri:0, instance:TestCases.TC_Login_Guru99_001@6f03482]" started-at="2023-10-06T19:19:45 IST" name="login" data-provider="Guru_Customer_Details" finished-at="2023-10-06T19:19:46 IST" duration-ms="1544" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[[Ljava.lang.Object;@58a765ce]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at TestCases.TC_Login_Guru99_001.login(TC_Login_Guru99_001.java:41)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="groupsstatus(java.lang.reflect.Method)[pri:0, instance:TestCases.TC_Login_Guru99_001@6f03482]" started-at="2023-10-06T19:19:45 IST" name="groupsstatus" finished-at="2023-10-06T19:19:45 IST" duration-ms="0" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void TestCases.TC_Login_Guru99_001.login(java.lang.Object[]) throws java.lang.InterruptedException,java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- groupsstatus -->
        <test-method is-config="true" signature="failedStatus(org.testng.ITestResult,java.lang.reflect.Method)[pri:0, instance:TestCases.TC_Login_Guru99_001@6f03482]" started-at="2023-10-06T19:19:47 IST" name="failedStatus" finished-at="2023-10-06T19:19:47 IST" duration-ms="419" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=login status=FAILURE method=TC_Login_Guru99_001.login([Ljava.lang.Object;)[pri:0, instance:TestCases.TC_Login_Guru99_001@6f03482] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void TestCases.TC_Login_Guru99_001.login(java.lang.Object[]) throws java.lang.InterruptedException,java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failedStatus -->
        <test-method is-config="true" signature="groupsstatus(java.lang.reflect.Method)[pri:0, instance:TestCases.TC_Login_Guru99_001@6f03482]" started-at="2023-10-06T19:19:47 IST" name="groupsstatus" finished-at="2023-10-06T19:19:47 IST" duration-ms="1" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void TestCases.TC_Login_Guru99_001.login(java.lang.Object[]) throws java.lang.InterruptedException,java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- groupsstatus -->
        <test-method signature="login([Ljava.lang.Object;)[pri:0, instance:TestCases.TC_Login_Guru99_001@6f03482]" started-at="2023-10-06T19:19:47 IST" name="login" data-provider="Guru_Customer_Details" finished-at="2023-10-06T19:19:50 IST" duration-ms="3115" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[[Ljava.lang.Object;@6b162ecc]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at TestCases.TC_Login_Guru99_001.login(TC_Login_Guru99_001.java:41)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="failedStatus(org.testng.ITestResult,java.lang.reflect.Method)[pri:0, instance:TestCases.TC_Login_Guru99_001@6f03482]" started-at="2023-10-06T19:19:51 IST" name="failedStatus" finished-at="2023-10-06T19:19:51 IST" duration-ms="466" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=login status=FAILURE method=TC_Login_Guru99_001.login([Ljava.lang.Object;)[pri:0, instance:TestCases.TC_Login_Guru99_001@6f03482] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void TestCases.TC_Login_Guru99_001.login(java.lang.Object[]) throws java.lang.InterruptedException,java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failedStatus -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:TestCases.TC_Login_Guru99_001@6f03482]" started-at="2023-10-06T19:19:51 IST" name="tearDown" finished-at="2023-10-06T19:19:52 IST" duration-ms="570" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="generateReports()[pri:0, instance:TestCases.TC_Login_Guru99_001@6f03482]" started-at="2023-10-06T19:19:52 IST" name="generateReports" finished-at="2023-10-06T19:19:53 IST" duration-ms="1321" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- generateReports -->
      </class> <!-- TestCases.TC_Login_Guru99_001 -->
    </test> <!-- Guru99 -->
  </suite> <!-- guru99 customer -->
</testng-results>
